# Generated by Django 5.1.2 on 2024-10-18 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the book.', max_length=255)),
                ('author', models.CharField(help_text='Author of the book.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of the book.')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price of the book.', max_digits=10)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like New'), ('used', 'Used'), ('worn', 'Worn')], default='used', help_text='Condition of the book.', max_length=20)),
                ('published_date', models.DateField(blank=True, help_text='Publication date of the book.', null=True)),
                ('image', models.ImageField(blank=True, help_text='Image of the book cover.', null=True, upload_to='book_images/')),
                ('is_available', models.BooleanField(default=True, help_text='Whether the book is still available for sale.')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time when the book was listed.')),
                ('seller', models.ForeignKey(help_text='The user who is selling the book.', on_delete=django.db.models.deletion.CASCADE, related_name='books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
